Title: null
Alternate Titles: null
Library: arcade
Series: null
Developer: null
Publisher: null
Play Mode: Single Player
Release Date: null
Version: null
Languages: en
Extreme: No
Tags: ""
Tag Categories: ""
Source: http://moyaimoment.github.io/test/idle-breakout/
Platform: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://moyaimoment.github.io/test/idle-breakout/
Game Notes: null
Original Description: null
Curation Notes: null
Mount Parameters: null
Additional Applications: {}
