Title: EDITHEREJHSDLKFJHAJKHDLKASHDKAJDS
Alternate Titles: null
Library: arcade
Series: null
Developer: null
Publisher: null
Play Mode: Single Player
Release Date: null
Version: null
Languages: en
Extreme: No
Tags: ""
Tag Categories: ""
Source: http://app-181839.games.s3.yandex.net/181839/0v5hmn3gqcl7uiqbx4r3bqpsne2106hw/index.html?app-id=181839&is-united-page=1&app-id=181839&is-united-page=1#&origin=https%3A%2F%2Fyandex.com&yandexapp=false&expBoxesCrypted=dIFf2x6b00AfU80agucANxpNJrtcBlJeW2TZc6VAv00187WVaUXAQBVe_UuTMR6W&experiments=%7B%22invalidate_games_cache_from%22%3A1654846446%2C%22web_apps_enabled%22%3Atrue%2C%22update_excluded_categories%22%3Atrue%2C%22adaptive_feed%22%3Atrue%2C%22adv_sticky_banner%22%3Atrue%2C%22adv_show_fullscreen_timeout%22%3A0%2C%22dj_experiment_param%22%3A%224%22%7D&app-id=181839&&origin=https%3A%2F%2Fyandex.ru&yandexapp=false&expBoxesCrypted=e39r1bu1JYtpZSbFSq-ypzFPQehbsv3jo-ViO5N7JjRkRTePuFRRNmxmfs7_3P_b&experiments=%7B%22invalidate_games_cache_from%22%3A1654846446%2C%22web_apps_enabled%22%3Atrue%2C%22update_excluded_categories%22%3Atrue%2C%22adaptive_feed%22%3Atrue%2C%22adv_sticky_banner%22%3Atrue%2C%22adv_show_fullscreen_timeout%22%3A0%2C%22adv_sticky_banner_desktop_additional_block%22%3Atrue%7D&app-id=181839
Platform: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://app-181839.games.s3.yandex.net/181839/0v5hmn3gqcl7uiqbx4r3bqpsne2106hw/index.html?app-id=181839&is-united-page=1&app-id=181839&is-united-page=1#&origin=https%3A%2F%2Fyandex.com&yandexapp=false&expBoxesCrypted=dIFf2x6b00AfU80agucANxpNJrtcBlJeW2TZc6VAv00187WVaUXAQBVe_UuTMR6W&experiments=%7B%22invalidate_games_cache_from%22%3A1654846446%2C%22web_apps_enabled%22%3Atrue%2C%22update_excluded_categories%22%3Atrue%2C%22adaptive_feed%22%3Atrue%2C%22adv_sticky_banner%22%3Atrue%2C%22adv_show_fullscreen_timeout%22%3A0%2C%22dj_experiment_param%22%3A%224%22%7D&app-id=181839&&origin=https%3A%2F%2Fyandex.ru&yandexapp=false&expBoxesCrypted=e39r1bu1JYtpZSbFSq-ypzFPQehbsv3jo-ViO5N7JjRkRTePuFRRNmxmfs7_3P_b&experiments=%7B%22invalidate_games_cache_from%22%3A1654846446%2C%22web_apps_enabled%22%3Atrue%2C%22update_excluded_categories%22%3Atrue%2C%22adaptive_feed%22%3Atrue%2C%22adv_sticky_banner%22%3Atrue%2C%22adv_show_fullscreen_timeout%22%3A0%2C%22adv_sticky_banner_desktop_additional_block%22%3Atrue%7D&app-id=181839
Game Notes: null
Original Description: null
Curation Notes: null
Mount Parameters: null
Additional Applications: {}
